version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  web:1 .
      - docker tag web:1 850752466801.dkr.ecr.ap-south-1.amazonaws.com/vishalcloud
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 850752466801.dkr.ecr.ap-south-1.amazonaws.com/vishalcloud
